syntax = "proto3";
package auth;

option go_package = "github.com/weit145/proto-startup/auth;auth";

message HealthDB {
    bool health = 1;
}

message Empty{}

message User {
  string id = 1;
  string email = 2;
  string username = 3;
  string role = 4;
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
}

message ConfirmRequest{
  string token = 1;
  string userID = 2;
}


message LoginRequest {
  string email = 1;
  string password = 2;
}

message LogOutRequest {
  string userID = 1;
  string refresh_token = 2;
}

message RefreshRequest {
  string refresh_token = 1;
}

message AuthResponse {
  string access_token = 1;
  string refresh_token = 2;
  User user = 3;
}

service Auth {
    rpc CheckHealth(Empty) returns (HealthDB);
    rpc Register(RegisterRequest) returns (Empty);
    rpc ConfirmEmail(ConfirmRequest) returns (AuthResponse);
    rpc Login(LoginRequest) returns (AuthResponse);
    rpc Logout(LogOutRequest) returns (Empty);
    rpc RefreshToken(RefreshRequest) returns (AuthResponse);
}
